/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.google.looker.app;


import org.apache.beam.sdk.Pipeline;
import org.apache.beam.sdk.options.PipelineOptions;
import org.apache.beam.sdk.options.PipelineOptionsFactory;
import org.apache.beam.sdk.transforms.Create;
import org.apache.beam.sdk.transforms.DoFn;
import org.apache.beam.sdk.transforms.ParDo;
import org.apache.beam.sdk.values.PCollection;

public class App {

  public static interface Options extends PipelineOptions {

  }

  public static void main(String[] args) {
    Options opts = PipelineOptionsFactory.fromArgs(args).as(Options.class);
    Pipeline pipeline = Pipeline.create(opts);
    PCollection<Integer> col = pipeline.apply("firstgo", Create.of(1, 2, 3));
    col.apply(
        ParDo.of(new DoFn<Integer, Void>() {
          @ProcessElement
          public void process(ProcessContext ctx) {
            System.out.println(ctx.element());
          }
        })
    );
    pipeline.run();

  }
}
